In [28]:
import sklearn
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
names =['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']
df = pd.read_csv('train.csv',header=None,sep=",",names=names, encoding = "ISO-8859-1")

In [30]:
df['toxic_score'] = df[['toxic','severe_toxic','obscene', 'threat', 'insult', 'identity_hate']].max(axis=1)
#drop unnecessary columns
df = df.drop(['id', 'toxic','severe_toxic','obscene', 'threat', 'insult', 'identity_hate'], axis=1)
#drop first row
df.drop(df.index[:1], inplace=True)
#df.drop(df.index[:150000], inplace=True) #smaller data set

In [31]:
print(df)

                                             comment_text toxic_score
1       Explanation\nWhy the edits made under my usern...           0
2       D'aww! He matches this background colour I'm s...           0
3       Hey man, I'm really not trying to edit war. It...           0
4       "\nMore\nI can't make any real suggestions on ...           0
5       You, sir, are my hero. Any chance you remember...           0
6       "\n\nCongratulations from me as well, use the ...           0
7            COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK           1
8       Your vandalism to the Matt Shirvington article...           0
9       Sorry if the word 'nonsense' was offensive to ...           0
10      alignment on this subject and which are contra...           0
11      "\nFair use rationale for Image:Wonju.jpg\n\nT...           0
12      bbq \n\nbe a man and lets discuss it-maybe ove...           0
13      Hey... what is it..\n@ | talk .\nWhat is it......           1
14      Before you s

In [32]:
df.head(5)

comment_text toxic_score
1  Explanation\nWhy the edits made under my usern...           0
2  D'aww! He matches this background colour I'm s...           0
3  Hey man, I'm really not trying to edit war. It...           0
4  "\nMore\nI can't make any real suggestions on ...           0
5  You, sir, are my hero. Any chance you remember...           0

In [33]:
bad_words = []
negative_file = open("negative-words.txt", "r")
for line in negative_file:
    bad_words.append(line.strip("\n"))
negative_file.close()
profanity_file = open("profanity-words.txt", "r")
for line in profanity_file:
    if (line.strip("\n") not in bad_words):
        bad_words.append(line.strip("\n"))
profanity_file.close()
# print(bad_words)

In [34]:
# # comment_list = df['comment_text'].to_numpy()
# comment_list = df['comment_text'].tolist()
# cv = sklearn.feature_extraction.text.CountVectorizer(vocabulary=bad_words)
# print(cv.fit_transform(comment_list).toarray())

In [35]:
data = df.values

X = data[:,0].reshape((159571,1))
Y = data[:,1].reshape((159571,1))

toxic_count = 0
not_toxic_count = 0

X_tr = []
Y_tr = []

for index in range(0,159571):
    if (int(Y[index][0]) == 1 and toxic_count < 7500) or (int(Y[index][0]) == 0 and not_toxic_count < 7500):
        Y_tr.append(int(Y[index][0]))
        X_tr.append(X[index][0])
        if (int(Y[index][0]) == 1):
            toxic_count += 1
        else:
            not_toxic_count += 1
    if toxic_count == 7500 and not_toxic_count == 7500:
        break

# X_tr = np.array(X_tr).reshape((15000, 1))
Y_tr = np.array(Y_tr).reshape((15000, 1))

cv = sklearn.feature_extraction.text.CountVectorizer(vocabulary=bad_words)
X_tr_features = cv.fit_transform(X_tr).toarray()

print(X_tr_features)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
